name: Build and Deploy bot

on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Artifact Registry
    runs-on: ubuntu-latest
    permissions:
      # packages: write
      # contents: read
      # attestations: write
      # id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'my-project'
          workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'


#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ env.GOOGLE_PROJECT_ID }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
#         with:
#           images: my-docker-hub-namespace/my-docker-hub-repository

#       - name: Build and push Docker image
#         id: push
#         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
#         with:
#           context: .
#           file: ./Dockerfile
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}

#       - name: Generate artifact attestation
#         uses: actions/attest-build-provenance@v2
#         with:
#           subject-name: index.docker.io/my-docker-hub-namespace/my-docker-hub-repository
#           subject-digest: ${{ steps.push.outputs.digest }}
#           push-to-registry: true
# jobs:
#   push_to_registry:
#     runs-on: ubuntu-latest
#     services:
#       mysql:
#         image: mysql:8.4.0
#         ports:
#           - 3306:3306
#         env:
#           MYSQL_DATABASE: creal_manager_test
#           MYSQL_ALLOW_EMPTY_PASSWORD: yes
#     env:
#       DATABASE_HOST: 127.0.0.1
#       DATABASE_USER: root
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       # Add or replace dependency steps here
#       - name: Install Ruby and gems
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.4.1
#           bundler-cache: true
#       - name: Set up database schema
#         run: bin/rake ridgepole:apply
#         env:
#           RAILS_ENV: test
#       - name: Run tests
#         run: bundle exec rspec
